import volatility.plugins.malware.idt as idt


def render_text(image, idt_hook_array):
    idt_class = idt.IDT(image)

    for n, entry, addr, module in idt_class.calculate():

        if addr == 0:
            module_name = "NOT USED"
        elif module:
            module_name = str(module.BaseDllName or '')
        else:
            module_name = "UNKNOWN"

        # The parent is IDT. The grand-parent is _KPCR.
        cpu_number = entry.obj_parent.obj_parent.ProcessorBlock.Number

        # is hooked ?
        if not module_name == winxpsp2x86[n]:
            idt_hook_array.append("cpu-{0}-index-{1:x}-module_name-{2}".format(cpu_number, n, module_name))


# clean image data
winxpsp2x86 = {0: 'ntoskrnl.exe',
               1: 'ntoskrnl.exe',
               2: 'NOT USED',
               3: 'ntoskrnl.exe',
               4: 'ntoskrnl.exe',
               5: 'ntoskrnl.exe',
               6: 'ntoskrnl.exe',
               7: 'ntoskrnl.exe',
               8: 'NOT USED',
               9: 'ntoskrnl.exe',
               10: 'ntoskrnl.exe',
               11: 'ntoskrnl.exe',
               12: 'ntoskrnl.exe',
               13: 'ntoskrnl.exe',
               14: 'ntoskrnl.exe',
               15: 'ntoskrnl.exe',
               16: 'ntoskrnl.exe',
               17: 'ntoskrnl.exe',
               18: 'ntoskrnl.exe',
               19: 'ntoskrnl.exe',
               20: 'ntoskrnl.exe',
               21: 'ntoskrnl.exe',
               22: 'ntoskrnl.exe',
               23: 'ntoskrnl.exe',
               24: 'ntoskrnl.exe',
               25: 'ntoskrnl.exe',
               26: 'ntoskrnl.exe',
               27: 'ntoskrnl.exe',
               28: 'ntoskrnl.exe',
               29: 'ntoskrnl.exe',
               30: 'ntoskrnl.exe',
               31: 'hal.dll',
               32: 'NOT USED',
               33: 'NOT USED',
               34: 'NOT USED',
               35: 'NOT USED',
               36: 'NOT USED',
               37: 'NOT USED',
               38: 'NOT USED',
               39: 'NOT USED',
               40: 'NOT USED',
               41: 'NOT USED',
               42: 'ntoskrnl.exe',
               43: 'ntoskrnl.exe',
               44: 'ntoskrnl.exe',
               45: 'ntoskrnl.exe',
               46: 'ntoskrnl.exe',
               47: 'ntoskrnl.exe',
               48: 'ntoskrnl.exe',
               49: 'ntoskrnl.exe',
               50: 'ntoskrnl.exe',
               51: 'ntoskrnl.exe',
               52: 'ntoskrnl.exe',
               53: 'ntoskrnl.exe',
               54: 'ntoskrnl.exe',
               55: 'hal.dll',
               56: 'ntoskrnl.exe',
               57: 'ntoskrnl.exe',
               58: 'ntoskrnl.exe',
               59: 'ntoskrnl.exe',
               60: 'ntoskrnl.exe',
               61: 'hal.dll',
               62: 'ntoskrnl.exe',
               63: 'ntoskrnl.exe',
               64: 'ntoskrnl.exe',
               65: 'hal.dll',
               66: 'ntoskrnl.exe',
               67: 'ntoskrnl.exe',
               68: 'ntoskrnl.exe',
               69: 'ntoskrnl.exe',
               70: 'ntoskrnl.exe',
               71: 'ntoskrnl.exe',
               72: 'ntoskrnl.exe',
               73: 'ntoskrnl.exe',
               74: 'ntoskrnl.exe',
               75: 'ntoskrnl.exe',
               76: 'ntoskrnl.exe',
               77: 'ntoskrnl.exe',
               78: 'ntoskrnl.exe',
               79: 'ntoskrnl.exe',
               80: 'hal.dll',
               81: 'ntoskrnl.exe',
               82: 'ntoskrnl.exe',
               83: 'ntoskrnl.exe',
               84: 'ntoskrnl.exe',
               85: 'ntoskrnl.exe',
               86: 'ntoskrnl.exe',
               87: 'ntoskrnl.exe',
               88: 'ntoskrnl.exe',
               89: 'ntoskrnl.exe',
               90: 'ntoskrnl.exe',
               91: 'ntoskrnl.exe',
               92: 'ntoskrnl.exe',
               93: 'ntoskrnl.exe',
               94: 'ntoskrnl.exe',
               95: 'ntoskrnl.exe',
               96: 'ntoskrnl.exe',
               97: 'ntoskrnl.exe',
               98: 'UNKNOWN',
               99: 'UNKNOWN',
               100: 'ntoskrnl.exe',
               101: 'ntoskrnl.exe',
               102: 'ntoskrnl.exe',
               103: 'ntoskrnl.exe',
               104: 'ntoskrnl.exe',
               105: 'ntoskrnl.exe',
               106: 'ntoskrnl.exe',
               107: 'ntoskrnl.exe',
               108: 'ntoskrnl.exe',
               109: 'ntoskrnl.exe',
               110: 'ntoskrnl.exe',
               111: 'ntoskrnl.exe',
               112: 'ntoskrnl.exe',
               113: 'ntoskrnl.exe',
               114: 'ntoskrnl.exe',
               115: 'UNKNOWN',
               116: 'ntoskrnl.exe',
               117: 'ntoskrnl.exe',
               118: 'ntoskrnl.exe',
               119: 'ntoskrnl.exe',
               120: 'ntoskrnl.exe',
               121: 'ntoskrnl.exe',
               122: 'ntoskrnl.exe',
               123: 'ntoskrnl.exe',
               124: 'ntoskrnl.exe',
               125: 'ntoskrnl.exe',
               126: 'ntoskrnl.exe',
               127: 'ntoskrnl.exe',
               128: 'ntoskrnl.exe',
               129: 'ntoskrnl.exe',
               130: 'UNKNOWN',
               131: 'UNKNOWN',
               132: 'ntoskrnl.exe',
               133: 'ntoskrnl.exe',
               134: 'ntoskrnl.exe',
               135: 'ntoskrnl.exe',
               136: 'ntoskrnl.exe',
               137: 'ntoskrnl.exe',
               138: 'ntoskrnl.exe',
               139: 'ntoskrnl.exe',
               140: 'ntoskrnl.exe',
               141: 'ntoskrnl.exe',
               142: 'ntoskrnl.exe',
               143: 'ntoskrnl.exe',
               144: 'ntoskrnl.exe',
               145: 'ntoskrnl.exe',
               146: 'UNKNOWN',
               147: 'UNKNOWN',
               148: 'ntoskrnl.exe',
               149: 'ntoskrnl.exe',
               150: 'ntoskrnl.exe',
               151: 'ntoskrnl.exe',
               152: 'ntoskrnl.exe',
               153: 'ntoskrnl.exe',
               154: 'ntoskrnl.exe',
               155: 'ntoskrnl.exe',
               156: 'ntoskrnl.exe',
               157: 'ntoskrnl.exe',
               158: 'ntoskrnl.exe',
               159: 'ntoskrnl.exe',
               160: 'ntoskrnl.exe',
               161: 'ntoskrnl.exe',
               162: 'ntoskrnl.exe',
               163: 'UNKNOWN',
               164: 'ntoskrnl.exe',
               165: 'ntoskrnl.exe',
               166: 'ntoskrnl.exe',
               167: 'ntoskrnl.exe',
               168: 'ntoskrnl.exe',
               169: 'ntoskrnl.exe',
               170: 'ntoskrnl.exe',
               171: 'ntoskrnl.exe',
               172: 'ntoskrnl.exe',
               173: 'ntoskrnl.exe',
               174: 'ntoskrnl.exe',
               175: 'ntoskrnl.exe',
               176: 'ntoskrnl.exe',
               177: 'UNKNOWN',
               178: 'UNKNOWN',
               179: 'ntoskrnl.exe',
               180: 'UNKNOWN',
               181: 'ntoskrnl.exe',
               182: 'ntoskrnl.exe',
               183: 'ntoskrnl.exe',
               184: 'ntoskrnl.exe',
               185: 'ntoskrnl.exe',
               186: 'ntoskrnl.exe',
               187: 'ntoskrnl.exe',
               188: 'ntoskrnl.exe',
               189: 'ntoskrnl.exe',
               190: 'ntoskrnl.exe',
               191: 'ntoskrnl.exe',
               192: 'ntoskrnl.exe',
               193: 'hal.dll',
               194: 'ntoskrnl.exe',
               195: 'ntoskrnl.exe',
               196: 'ntoskrnl.exe',
               197: 'ntoskrnl.exe',
               198: 'ntoskrnl.exe',
               199: 'ntoskrnl.exe',
               200: 'ntoskrnl.exe',
               201: 'ntoskrnl.exe',
               202: 'ntoskrnl.exe',
               203: 'ntoskrnl.exe',
               204: 'ntoskrnl.exe',
               205: 'ntoskrnl.exe',
               206: 'ntoskrnl.exe',
               207: 'ntoskrnl.exe',
               208: 'ntoskrnl.exe',
               209: 'hal.dll',
               210: 'ntoskrnl.exe',
               211: 'ntoskrnl.exe',
               212: 'ntoskrnl.exe',
               213: 'ntoskrnl.exe',
               214: 'ntoskrnl.exe',
               215: 'ntoskrnl.exe',
               216: 'ntoskrnl.exe',
               217: 'ntoskrnl.exe',
               218: 'ntoskrnl.exe',
               219: 'ntoskrnl.exe',
               220: 'ntoskrnl.exe',
               221: 'ntoskrnl.exe',
               222: 'ntoskrnl.exe',
               223: 'ntoskrnl.exe',
               224: 'ntoskrnl.exe',
               225: 'hal.dll',
               226: 'ntoskrnl.exe',
               227: 'hal.dll',
               228: 'ntoskrnl.exe',
               229: 'ntoskrnl.exe',
               230: 'ntoskrnl.exe',
               231: 'ntoskrnl.exe',
               232: 'ntoskrnl.exe',
               233: 'ntoskrnl.exe',
               234: 'ntoskrnl.exe',
               235: 'ntoskrnl.exe',
               236: 'ntoskrnl.exe',
               237: 'ntoskrnl.exe',
               238: 'ntoskrnl.exe',
               239: 'ntoskrnl.exe',
               240: 'ntoskrnl.exe',
               241: 'ntoskrnl.exe',
               242: 'ntoskrnl.exe',
               243: 'ntoskrnl.exe',
               244: 'ntoskrnl.exe',
               245: 'ntoskrnl.exe',
               246: 'ntoskrnl.exe',
               247: 'ntoskrnl.exe',
               248: 'ntoskrnl.exe',
               249: 'ntoskrnl.exe',
               250: 'ntoskrnl.exe',
               251: 'ntoskrnl.exe',
               252: 'ntoskrnl.exe',
               253: 'hal.dll',
               254: 'hal.dll',
               255: 'ntoskrnl.exe'}
